version: '3.8'

services:
   serve:
      image: getchoo/packwiz-serve:latest
      volumes:
         - ./pack:/data

   install:
      image: itzg/minecraft-server:latest
      environment:
         EULA: 'TRUE'
         SETUP_ONLY: 'TRUE'
         PACKWIZ_URL: http://serve:8080/pack.toml
      volumes:
         - ./install:/data
