services:
   serve:
      image: ghcr.io/voidshake/packwiz-serve:latest
      volumes:
         - ./pack:/data
      ports:
         - 8088:80

   install:
      image: itzg/minecraft-server:latest
      environment:
         EULA: 'TRUE'
         SETUP_ONLY: 'TRUE'
         PACKWIZ_URL: http://serve/pack.toml
      volumes:
         - ./install:/data
      depends_on:
         - serve
