name = "Arva"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f665ed954363cee93b656ad060de7ef8a22633da78b30cbeab5f4a5f8ad98153"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.2", "1.20.1", "1.21"]
