name = "Arva"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0825f160b364eaef4fd6b495f614e91967a421c963a114cfc01bfab1383bea3"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.2", "1.20.1", "1.21"]
